#+CATEGORY: luad

[[https://doi.org/10.5281/zenodo.16379014][https://zenodo.org/badge/379043826.svg]]

* Objective

To study the mutational and adaptive landscape of lung adenocarcinoma (LUAD)
and how it is altered by the mutagenic and physiological effects of tobacco
smoking using an aggregated dataset of LUAD genomes.

* Requirements

- Python, ideally installed with pyenv
  (https://github.com/pyenv/pyenv) to be able to have exactly the same
  version (3.9.5) as the tested, but otherwise at least 3.7 so that
  the order of dictionaries is preserved.
- R (in debian or ubuntu install the packages r-base and r-base-dev)
- the development files for libcurl (OpenSSL flavour) are required for
  many R packages including RCurl (that is required for
  cancereffectsizeR). In debian or ubuntu install the
  libcurl4-openssl-dev package

* Setup

To prepare the system for running the analysis, within the ==code==
directory run
#+begin_src shell
  ./setup.sh
#+end_src
and follow the instructions.

* Analysis

To run the analysis, within the ==code== directory run
#+begin_src shell
  cd variants
  Rscript main.R
  cd ../
  source .venv/bin/activate
  python main.py
#+end_src

Results can be analyzed using the provided jupyter notebooks in the
==result_analysis== directory.
